### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by marcelvanherk** [spectra/conquest-dicom-server#1]
Just went though the patches and commented on them. Merged changes (sometimes modified) into 1.4.17d

Marcel

**Comment by spectra** [comment]
Great. I took some days off. Be back on 23rd. I'll resume working then.

On 15 de fevereiro de 2014 21h08min37s BRT, marcelvanherk notifications@github.com wrote:

> Just went though the patched and commented on them. Merged changes
> (sometimes modified) into 1.4.17d
> 
> Marcel
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/spectra/conquest-dicom-server/issues/1

## 

E-mail enviado do meu celular Android usando K-9 Mail. Por favor, desculpe minha brevidade.

**Comment by spectra** [comment]
All of those were reviewed, modified where needed and refreshed. Most of them were applied upstream with 1.4.17d and removed from debian/patches.
